title: sEverely n0ted
description: A scratchpad
remote_theme: just-the-docs/just-the-docs

# This ensures the search function works correctly
url: "https://sEver.github.io"
baseurl: "/" 

# Optional: Add a link to your GitHub repo in the top right
aux_links:
  "GitHub Repository": "https://github.com/sEver/sEver.github.io"
